In [5]:
from factor import *

In [25]:
A = Factor(var=[0],
                     card=[2],
                     val=[0.8, 0.2])
B = Factor(var=[0, 1],
                     card=[2, 2],
                     val=[0.4, 0.55, 0.6, 0.45])

In [26]:
print(A)
print(B)

Factor containing 1 variables
---------------------
| X_0 | Probability |
---------------------
|  0  |         0.8 |
|  1  |         0.2 |
---------------------


Factor containing 2 variables
-------------------------
| X_0 X_1 | Probability |
-------------------------
|  0   0  |         0.4 |
|  1   0  |        0.55 |
|  0   1  |         0.6 |
|  1   1  |        0.45 |
-------------------------




In [27]:
def factor_product(A, B):
    """Compute product of two factors.

    Suppose A = phi(X_1, X_2), B = phi(X_2, X_3), the function should return
    phi(X_1, X_2, X_3)
    """
    if A.is_empty():
        return B
    if B.is_empty():
        return A

    # Create output factor. Variables should be the union between of the
    # variables contained in the two input factors
    out = Factor()
    out.var = np.union1d(A.var, B.var)
    #print(out.var)
    out.card = np.zeros(len(out.var), np.int64)
    # print(out.card)
    mapA = np.argmax(out.var[None, :] == A.var[:, None], axis=-1)
    #print(mapA)
    mapB = np.argmax(out.var[None, :] == B.var[:, None], axis=-1)
    #print(mapB)
    out.card[mapA] = A.card
    out.card[mapB] = B.card
    # print(out.card)
    out.val = np.zeros(np.prod(out.card))
    # print(out.val)
    assignments = out.get_all_assignments()
    print(assignments)
    idxA = assignment_to_index(assignments[:, mapA], A.card)
    # print(assignments[:, mapA])
    print(idxA)
    idxB = assignment_to_index(assignments[:, mapB], B.card)
    print(idxB)
    out.val = A.val[idxA]*B.val[idxB]
    print(out)

factor_product(A,B)

[[0 0]
 [1 0]
 [0 1]
 [1 1]]
[0 1 0 1]
[0 1 2 3]
Factor containing 2 variables
-------------------------
| X_0 X_1 | Probability |
-------------------------
|  0   0  |        0.32 |
|  1   0  |        0.11 |
|  0   1  |        0.48 |
|  1   1  |        0.09 |
-------------------------


